services:
  traefik:
    image: "traefik"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=mytlschallenge"
      - "traefik.http.middlewares.dashboard.stripprefix.prefixes=/dashboard"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      # Uncomment for staging.
      # - "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mixpost:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9000:9000
    environment:
      PHP_FPM_LISTEN: 9000
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE-mixpost}
      DB_USERNAME: ${DB_USERNAME-mixpost}
      DB_PASSWORD: ${DB_PASSWORD-changeme}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-rootchangeme}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./store/mixpost:/var/www/html/storage/app
      - ./logs/mixpost:/var/www/html/storage/logs
      - ./logs/php/php8.2-fpm.log:/var/log/php8.2-fpm.log
      - public:/var/www/html/public
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default-local.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - public:/var/www/html/public
    depends_on:
      - mixpost
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls.certresolver=mytlschallenge
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.middlewares.nginx-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.nginx-headers.headers.STSSeconds=315360000
      - traefik.http.middlewares.nginx-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.nginx-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nginx-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.nginx-headers.headers.SSLHost=${APP_DOMAIN}
      - traefik.http.middlewares.nginx-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.nginx-headers.headers.STSPreload=true
      - traefik.http.routers.nginx.middlewares=nginx-headers@docker

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: ${DB_DATABASE-mixpost}
      MARIADB_USER: ${DB_USERNAME-mixpost}
      MARIADB_PASSWORD: ${DB_PASSWORD-changeme}
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-rootchangeme}
    volumes:
      - "mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    command:
      [
        "--log-bin=mysqld-bin",
        "--max-connections=1000",
        "--wait-timeout=28800",
        "--bind-address=0.0.0.0",
      ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mariadb -h localhost -u root -p"${DB_ROOT_PASSWORD-rootchangeme}" -e "SELECT 1;"',
        ]
      start_period: 30s
      retries: 10
      timeout: 10s
    restart: unless-stopped

  redis:
    image: "redis:latest"
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

volumes:
  traefik_data:
    driver: local
  mariadb:
    driver: local
  redis:
    driver: local
  public:
    driver: local
